const router = require('express').Router();

const optionsArray = [
  {
    option: 'frontend',
    label: 'Frontend',
    type: 'type',
    requiredBy: [],
    compatibleWith: [],
    description: 'A frontend for your application',
    version: '',
    documentationLink: '',
    logo: '',
  },
  {
    option: 'backend',
    label: 'Backend',
    type: 'type',
    requiredBy: [],
    compatibleWith: [],
    description: 'A backend for your application',
    version: '',
    documentationLink: '',
    logo: ''
  },
  {
    option: 'database',
    label: 'Database',
    type: 'type',
    requiredBy: [],
    compatibleWith: [],
    description: 'A database for your application',
    version: '',
    documentationLink: '',
    logo: '',
  },
  {
    option: 'javascript',
    label: 'JavaScript',
    type: 'language',
    requiredBy: [],
    compatibleWith: ['frontend', 'backend'],
    description: 'A high-level, interpreted programming language',
    version: 'ES2021',
    documentationLink: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png',
  },
  {
    option: 'python',
    label: 'Python',
    type: 'language',
    requiredBy: [],
    compatibleWith: ['backend'],
    description: 'An interpreted, high-level and general-purpose programming language',
    version: '3.9.5',
    documentationLink: 'https://www.python.org/doc/',
    logo: 'https://www.python.org/static/community_logos/python-logo.png',
  },
  {
    option: 'react',
    label: 'React',
    type: 'framework',
    requiredBy: ['frontend', 'javascript'],
    compatibleWith: [],
    description: 'A JavaScript library for building user interfaces',
    version: '17.0.2',
    documentationLink: 'https://reactjs.org/',
    logo: 'https://reactjs.org/logo-og.png',
  },
  {
    option: 'node',
    label: 'Node.js',
    type: 'runtime',
    requiredBy: ['javascript'],
    compatibleWith: ['frontend', 'backend'],
    description: 'JavaScript runtime built on Chrome\'s V8 JavaScript engine',
    version: '14.17.1',
    documentationLink: 'https://nodejs.org/en/docs/',
    logo: 'https://nodejs.org/static/images/logo.svg',
  },
  {
    option: 'bun',
    label: 'Bun',
    type: 'runtime',
    requiredBy: ['javascript'],
    compatibleWith: ['frontend', 'backend'],
    description: 'Bun is a fast, all-in-one toolkit for running, building, testing, and debugging JavaScript and TypeScript, from a single file to a full-stack application.',
    version: '1.0.11',
    documentationLink: 'https://bun.sh/docs',
    logo: 'https://bun.sh/logo.svg',
  },
  {
    option: 'express',
    label: 'Express',
    type: 'framework',
    requiredBy: ['backend', 'javascript'],
    compatibleWith: [],
    description: 'Fast, unopinionated, minimalist web framework for Node.js',
    version: '4.17.1',
    documentationLink: 'https://expressjs.com/',
    logo: 'https://expressjs.com/images/express-facebook-share.png',
  },
  {
    option: 'flask',
    label: 'Flask',
    type: 'framework',
    requiredBy: ['backend', 'python'],
    compatibleWith: [],
    description: 'A lightweight WSGI web application framework',
    version: '1.1.2',
    documentationLink: 'https://flask.palletsprojects.com/',
    logo: 'https://flask.palletsprojects.com/en/1.1.x/_images/flask-logo.png',
  },
  {
    option: 'django',
    label: 'Django',
    type: 'framework',
    requiredBy: ['backend', 'python'],
    compatibleWith: [],
    description: 'The web framework for perfectionists with deadlines',
    version: '3.2.4',
    documentationLink: 'https://www.djangoproject.com/',
    logo: 'https://www.djangoproject.com/m/img/logos/django-logo-negative.png',
  },
  {
    option: 'postgres',
    label: 'PostgreSQL',
    type: 'database',
    requiredBy: ['database'],
    compatibleWith: [],
    description: 'The world\'s most advanced open source relational database',
    version: '13.3',
    documentationLink: 'https://www.postgresql.org/docs/',
    logo: 'https://www.postgresql.org/media/img/about/press/elephant.png',
  },
  {
    option: 'mongodb',
    label: 'MongoDB',
    type: 'database',
    requiredBy: ['database'],
    compatibleWith: [],
    description: 'The database for modern applications',
    version: '4.4.6',
    documentationLink: 'https://docs.mongodb.com/',
    logo: 'https://www.mongodb.com/assets/images/global/favicon.ico',
  }
];

router.get('/', (req, res) => {
  res.send(optionsArray);
});

module.exports = router;