const fs = require('fs');
const path = require('path');

const exampleService = {
  "id": 0,
  "app": "PERN Template",
  "name": "Client",
  "language": "javascript",
  "technology": "",
  "framework": "react",
  "database": "",
  "subdirectory": "",
  "runtime": "node",
  "image": "node:latest",
  "type": "frontend",
  "port": "3000"
}

function createDockerFile(cwd, service) {
  let { name, language, technology, framework, database, subdirectory, runtime, type, port, image } = service;

  if (!port) { port = 3000; }
  if (!image) { image = 'node:latest'; }

  const dockerFile = `
  # This dockerfile was generated by TRACER for app ${name}

  # Pull base image
  FROM ${image}

  # Set working directory
  WORKDIR /usr/src/app

  # Install app dependencies
  COPY package*.json ./
  RUN npm install

  # Copy app files
  COPY . .

  # Start the app
  EXPOSE ${port}

  # Run the app
  CMD [ "npm", "start" ]
  `

  fs.writeFileSync(path.join(cwd, 'Dockerfile'), dockerFile);
}

module.exports = {
  createDockerFile
};